import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 68,
    paddingBottom: 16,
    justifyContent: 'space-between',
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 8,
    elevation: 6,
  },
  nome: {
    fontSize: 20,
    fontWeight: '800',
    color: '#222222',
    textAlign: 'center',
    marginBottom: 10,
  },
  descricao: {
    fontSize: 14,
    color: '#444444',
    textAlign: 'left',
    marginBottom: 14,
  },
  blocoPreco: {
    alignItems: 'flex-start',
  },
  preco: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ff4b2b',
  },
  footer: {
    width: '100%',
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: 0,
    backgroundColor: 'transparent',
  },
  controleQuantidade: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  botaoQuantidade: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.96)',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 4,
    elevation: 3,
  },
  textoQuantidade: {
    fontSize: 20,
    fontWeight: '800',
    color: '#222222',
  },
  valorQuantidade: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    minWidth: 36,
    textAlign: 'center',
  },
  botaoAdicionar: {
    backgroundColor: '#ff4b2b',
    height: 52,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 8,
    elevation: 6,
  },
  textoBotao: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
});
